### ISSUE TITLE
train.py value error !!

### ISSUE THREAD

**Issue by us** [Kyubyong/word_prediction#1]
I've taken the first 4 steps and I'm getting this error at 5th.

`ValueError: Index out of range using input dim 0; input has only 0 dims for 'strided_slice' (op: 'StridedSlice') with input shapes: [], [1], [1], [1].`

**Comment by Kyubyong** [comment]
Which line does the error message point to? Check if the generated corpus and training data are the same as mine: https://drive.google.com/open?id=0B0ZXk88koS2KemFWdFNoSnBfNDg.

**Comment by saritekin** [comment]
I downloaded your data. But I still get that error.My all error :

```
Traceback (most recent call last):
  File "train.py", line 97, in <module>
    train(); print("Done")
  File "train.py", line 90, in train
    g = ModelGraph()
  File "train.py", line 68, in __init__
    self.x, self.y, self.num_batch = get_batch_data() 
  File "train.py", line 43, in get_batch_data
    x_q, y_q = q_process(x_q, y_q) # (50,) int32, () int32
  File "train.py", line 16, in q_process
    t1 = t1[zeros:] 
  File "/home/syny/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 436, in _SliceHelper
    name=name)
  File "/home/syny/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 590, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/home/syny/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3503, in strided_slice
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "/home/syny/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/home/syny/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2242, in create_op
    set_shapes_for_outputs(ret)
  File "/home/syny/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1617, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/syny/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1568, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/syny/.local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/home/syny/.local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Index out of range using input dim 0; input has only 0 dims for 'strided_slice' (op: 'StridedSlice') with input shapes: [], [1], [1], [1].
```

**Comment by Aashit-Sharma** [comment]
same issue. [please check thisout](https://github.com/tensorflow/tensorflow/issues/16279)
