### ISSUE TITLE
Module error 

### ISSUE THREAD

**Issue by SoorajBP** [Kyubyong/word_prediction#8]
I keep getting error while running eval.py 
Traceback (most recent call last):
  File "C:\Users\V\Documents\word_prediction-master\eval.py", line 20, in <module>
    import sugartensor as tf
  File "C:\Python27\lib\site-packages\sugartensor\__init__.py", line 2, in <module>
    from tensorflow import *
AttributeError: module  'tensorflow' has no attribute 'core'

I have installed all modules as per requirement .

**Comment by Swathi245** [comment]
Traceback (most recent call last):
  File "C:\python3\word_prediction-master\eval.py", line 20, in <module>
    import sugartensor as tf
  File "C:\Users\DELL\Anaconda3\lib\site-packages\sugartensor\__init__.py", line 2, in <module>
    from tensorflow import *
AttributeError: module 'tensorflow' has no attribute 'core'
im getting error like this 
what is the solution anyone pls
