### ISSUE TITLE
 AttributeError: module 'tensorflow' has no attribute 'core'

### ISSUE THREAD

**Issue by Swathi245** [Kyubyong/word_prediction#9]
Traceback (most recent call last):
  File "C:\python3\word_prediction-master\eval.py", line 20, in <module>
    import sugartensor as tf
  File "C:\Users\DELL\Anaconda3\lib\site-packages\sugartensor\__init__.py", line 2, in <module>
    from tensorflow import *
AttributeError: module 'tensorflow' has no attribute 'core'
Any solution

**Comment by Muhammad057** [comment]
@Swathi245 how did you resolve this error?
